site_name: Information and Decision Sciences PhD Program — Carlson School of Management
site_description: Supplemental information and FAQs for prospective students considering the Information and Decision Sciences PhD program at the University of Minnesota's Carlson School of Management.
site_url: https://de4liu.github.io/ids-phd-public/
theme:
  name: material
  icon:
    logo: material/school
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
    - Home: index.md
    - Considering an IDS PhD?: considering-the-phd.md
    - Official Resources: official-resources.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

copyright: |
  &copy; 2026 Dr. De Liu, PhD Coordinator, Information and Decision Sciences, Carlson School of Management, University of Minnesota.